# Generated by Django 3.0.4 on 2020-04-28 15:48

import thessia.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thessia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last modified')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('author', models.CharField(max_length=200, verbose_name='autor')),
                ('description', models.CharField(max_length=500, verbose_name='descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to=thessia.utils.image_upload_location, verbose_name='imagen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_cuento_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beers_cuento_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Cuento',
                'verbose_name_plural': 'Cuentos',
                'ordering': ['-title'],
            },
        ),
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
