# Generated by Django 3.0.4 on 2020-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thessia', '0003_auto_20200428_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
