# Generated by Django 3.0.4 on 2020-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thessia', '0009_pruebauno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def1', models.CharField(max_length=200, verbose_name='concepto')),
                ('def2', models.CharField(max_length=200, verbose_name='definicion')),
                ('def3', models.CharField(max_length=200, verbose_name='definicion')),
            ],
            options={
                'verbose_name': 'PruebaTres',
                'verbose_name_plural': 'PruebasTres',
                'ordering': ['-def1'],
            },
        ),
    ]
