# Generated by Django 3.0.4 on 2020-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thessia', '0011_auto_20200527_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pruebatres',
            options={'ordering': ['-pk'], 'verbose_name': 'PruebaTres', 'verbose_name_plural': 'PruebasTres'},
        ),
    ]
